# Go environment
export GOPATH="$HOME/Projects/go"
export GOPATH_BIN="$GOPATH/bin"

# Fuck you, Google
export GOPROXY=direct
export GOSUMDB=off
export GOTELEMETRY=off
export GOTOOLCHAIN=local

export ADB_MDNS=0

DOOM_EMACS="$HOME/.emacs.d/bin"

case $(uname -s) in
"Linux")
	#export JAVA_HOME=$(echo $JAVA_HOME)

	export ANDROID_HOME="$HOME/Android/Sdk"
	#ANDROID_PLATFORM_TOOLS="$ANDROID_HOME/platform-tools"
	#ANDROID_BUILD_TOOLS="$ANDROID_HOME/build-tools/34.0.0"
	;;
"Darwin")
	# Fuck you, Homebrew
	export HOMEBREW_NO_ANALYTICS=1
	export HOMEBREW_NO_GOOGLE_ANALYTICS=1

	export JAVA_HOME=$(/usr/libexec/java_home)

	LATEX_PATH="/Library/TeX/texbin"
	SBIN_PATH="/usr/local/sbin"

	VSCODIUM_PATH="$HOME/Applications/VSCodium.app/Contents/Resources/app/bin"

	export ANDROID_HOME="$HOME/Library/Android/sdk"
	ANDROID_PLATFORM_TOOLS="$ANDROID_HOME/platform-tools"
	ANDROID_BUILD_TOOLS="$ANDROID_HOME/build-tools/35.0.0"

	# Mutt charset
	export LC_ALL=es_ES.UTF-8

	DOOM_EMACS="$HOME/.config/emacs/bin/"

	export PATH="$PATH:$SBIN_PATH:$LATEX_PATH:$ANDROID_PLATFORM_TOOLS:$ANDROID_BUILD_TOOLS:$VSCODIUM_PATH"
	;;
esac

export PATH="$PATH:$GOPATH:$GOPATH_BIN:$DOOM_EMACS"
