# Go environment
export GOPATH="$HOME/Projects/go"
export GOPATH_BIN="$GOPATH/bin"

case $(uname -s) in
	"Linux")
		export JAVA_HOME="/usr/lib/jvm/default"

		CORE_PERL="/usr/bin/core_perl"
		AND_PLATOOLS="$HOME/Android/Sdk/platform-tools"
		AND_TOOLS="$HOME/Android/Sdk/android-sdk/tools"

		export PATH="$PATH:$CORE_PERL:$AND_PLATOOLS"
		;;
	"Darwin")
		export JAVA_HOME=$(/usr/libexec/java_home)

		SBIN_PATH="/usr/local/sbin"
		LATEX_PATH="/Library/TeX/texbin"
		CODE_PATH="/Applications/VSCodium.app/Contents/Resources/app/bin"

		AND_TOOLS="$HOME/Library/Android/sdk/platform-tools/"

		# Mutt charset
		export LC_ALL=es_ES.UTF-8

		export PATH="$PATH:$SBIN_PATH:$LATEX_PATH:$CODE_PATH"
		;;
esac

DOTFILES_BIN="$HOME/.dotfiles/bin"

export PATH="$PATH:$GOPATH:$GOPATH_BIN:$DOTFILES_BIN:$AND_TOOLS"

fpath+=~/.zfunc
