DOTFILES_BIN="$HOME/.dotfiles/bin"

# Go environment
export GOPATH="$HOME/Projects/go"
export GOPATH_BIN="$GOPATH/bin"

# Fuck you, Google
export GOPROXY=direct
export GOSUMDB=off
export GOTELEMETRY=off
export GOTOOLCHAIN=local

export ADB_MDNS=0

case $(uname -s) in
"Linux")
	export JAVA_HOME="/usr/lib/jvm/default"

	export ANDROID_HOME="$HOME/Android/Sdk"
	ANDROID_PLATFORM_TOOLS="$ANDROID_HOME/platform-tools"
	ANDROID_BUILD_TOOLS="$ANDROID_HOME/build-tools/33.0.2"

	CORE_PERL="/usr/bin/core_perl"

	LOCAL_BIN="$HOME/.local/bin"

	export PATH="$PATH:$CORE_PERL"
	;;
"Darwin")
	# Fuck you, Homebrew
	export HOMEBREW_NO_ANALYTICS=1
	export HOMEBREW_NO_GOOGLE_ANALYTICS=1

	export JAVA_HOME=$(/usr/libexec/java_home)

	LATEX_PATH="/Library/TeX/texbin"
	SBIN_PATH="/usr/local/sbin"
	VSCODIUM_PATH="/Applications/VSCodium.app/Contents/Resources/app/bin"

	export ANDROID_HOME="$HOME/Library/Android/sdk"
	ANDROID_PLATFORM_TOOLS="$ANDROID_HOME/platform-tools"
	ANDROID_BUILD_TOOLS="$ANDROID_HOME/build-tools/33.0.0"

	EMACS="/Applications/Emacs.app/Contents/MacOS"
	EMACSCLIENT="/Applications/Emacs.app/Contents/MacOS/bin"

	PYTHON_BIN="$HOME/Library/Python/3.10/bin"

	LOCAL_BIN="$HOME/.local/bin"

	# Mutt charset
	export LC_ALL=es_ES.UTF-8

	export PATH="$PATH:$SBIN_PATH:$LATEX_PATH:$VSCODIUM_PATH:$EMACS:$EMACSCLIENT:$PYTHON_BIN"
	;;
esac

export PATH="$PATH:$GOPATH:$GOPATH_BIN:$DOTFILES_BIN:$ANDROID_PLATFORM_TOOLS:$ANDROID_BUILD_TOOLS:$LOCAL_BIN"

fpath+=~/.zfunc
