# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="candy_mod2"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# Go env vars
export GOPATH="$HOME/Projects/go"
export GOPATH_BIN="$GOPATH/bin"
# Rust env var
export RUST_PATH="$HOME/Projects/.cargo/bin"

# User configuration
case $(uname -s) in
	"Linux")
		NEW_PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/bin/core_perl"
		AND_PLATOOLS="/opt/android-sdk/platform-tools"
		export PATH="$NEW_PATH:$GOPATH:$GOPATH_BIN:$AND_PLATOOLS"
		;;
	"Darwin")
		LATEX_PATH="/Library/TeX/texbin"
		CODE_PATH="/Applications/VSCodium.app/Contents/Resources/app/bin"
		NEW_PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
		export PATH="$NEW_PATH:$GOPATH:$GOPATH_BIN:$LATEX_PATH:$CODE_PATH"
		# Mutt charset
		export LC_ALL=es_ES.UTF-8
		;;
esac

export PATH="$PATH:$RUST_PATH"

fpath+=~/.zfunc

# Other variables
export TERM=xterm-256color mutt
source $ZSH/oh-my-zsh.sh
source $HOME/.bash_aliases

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Compilation flags
# export ARCHFLAGS="-arch x86_64"
